// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taskify.Server.Data;

#nullable disable

namespace Taskify.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231014070454_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Taskify.Shared.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedTime = new DateTime(2023, 10, 14, 9, 4, 54, 647, DateTimeKind.Local).AddTicks(7323),
                            Category = 0,
                            Description = "Prepare slides and rehearse for the project presentation.",
                            Status = 0,
                            Title = "Complete Project Presentation"
                        },
                        new
                        {
                            Id = 2,
                            AddedTime = new DateTime(2023, 10, 13, 9, 4, 54, 647, DateTimeKind.Local).AddTicks(7326),
                            Category = 3,
                            Description = "Enjoy a 30-minute jog in the park.",
                            Status = 1,
                            Title = "Go for a Run"
                        },
                        new
                        {
                            Id = 3,
                            AddedTime = new DateTime(2023, 10, 12, 9, 4, 54, 647, DateTimeKind.Local).AddTicks(7335),
                            Category = 2,
                            Description = "Study and take notes on chapter 3 of the machine learning book.",
                            Status = 2,
                            Title = "Read Chapter 3 of 'Machine Learning Fundamentals'"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
